apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectstorage-provisioner
  labels:
{{ include "s3gw-cosi.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
{{ include "s3gw-cosi.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "s3gw-cosi.selectorLabels" . | indent 8 }}
    spec:
      serviceAccountName: objectstorage-provisioner-sa
      volumes:
        - name: socket
          emptyDir: {}
      containers:
        - name: s3gw-cosi-driver
          image: {{ include "s3gw-cosi.driverImage" . | quote }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.driver.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: objectstorage-provisioner
          volumeMounts:
            - mountPath: /var/lib/cosi
              name: socket
        - name: objectstorage-provisioner-sidecar
          image: {{ include "s3gw-cosi.sidecarImage" . | quote }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.sidecar.imagePullPolicy }}
          args:
            - {{ printf "--v=%s" (default "1" .Values.sidecar.logLevel) }}
          envFrom:
            - secretRef:
                name: objectstorage-provisioner
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/lib/cosi
              name: socket
