---
driver:
  imageName:
  imageTag:
  imageRegistry:
  imagePullPolicy:

sidecar:
  imageName:
  imageTag:
  imageRegistry:
  imagePullPolicy:
  logLevel: "5"

s3gw:
  endpoint: "http://s3gw.s3gw.svc.cluster.local"
  accessKey: "test"
  secretKey: "test"
