apiVersion: v1
kind: Pod
metadata:
  namespace: sample-ns
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    volumeMounts:
      - name: cosi-secrets
        mountPath: /data/cosi
    args:
      - sleep
      - "1000"
    resources:
      requests:
        cpu: "0.5"
      limits:
        memory: "500Mi"
        cpu: "1"
  volumes:
    - name: cosi-secrets
      secret:
        secretName: sample-bc-secret
